{{- if .Values.serviceMonitor.enabled }}
{{- range .Values.signers }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: tezos-signer-forwarder
  name: tezos-remote-signer-monitoring-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  endpoints:
  - port: metrics
    path: /metrics
    # default scrape timeout of 10 can be too small for remote raspberry pis
    scrapeTimeout: "20s"
  selector:
    matchLabels:
      app.kubernetes.io/name: tezos-signer-forwarder
      midl_baker_name: {{ .name }}
  targetLabels:
  - midl_baker_name
---
{{- end }}
{{- end }}
