apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-ssh-ingress-{{ .Values.name }}
  annotations:
{{ toYaml .Values.service_annotations | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tezos-signer-forwarder
  ports:
{{- range .Values.signers }}
{{- $name := .name }}
{{- $signers := . }}
{{- range $i := until (len .endpoints) }}
{{- $endpoint := index $signers.endpoints $i }}
  - port: {{ $endpoint.tunnel_endpoint_port }}
    name: tunnel-{{ $name }}-{{ $i }}
{{- end }}
{{- end }}
  # ensures that remote signers can always ssh
  publishNotReadyAddresses: true
{{ if .Values.load_balancer_ip }}
  loadBalancerIP: {{ .Values.load_balancer_ip }}
{{ end }}
---
{{- range .Values.signers }}
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-{{ .name }}
  labels:
    app.kubernetes.io/name: tezos-signer-forwarder
    app.kubernetes.io/baker-name: {{ .name }}
spec:
  selector:
    app.kubernetes.io/name: tezos-signer-forwarder
    app.kubernetes.io/baker-name: {{ .name }}
  ports:
  - port: {{ .signer_port }}
    name: signer
  - port: 31732
    name: metrics
  # make sure that the service always targets the same signer, when HA is in use.
  sessionAffinity: ClientIP
---
{{- end }}
