apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-ssh-ingress-{{ .Values.name }}
  annotations:
{{ toYaml .Values.service_annotations | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tezos-signer-forwarder
  ports:
{{- range .Values.endpoints }}
  - port: {{ .tunnel_endpoint_port }}
    name: tunnel-{{ .name }}
{{- end }}
  # ensures that remote signers can always ssh
  publishNotReadyAddresses: true
---
{{- range .Values.endpoints }}
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-{{ .name }}
  labels:
    app.kubernetes.io/name: tezos-signer-forwarder
    app.kubernetes.io/baker-name: {{ .name }}
spec:
  selector:
    app.kubernetes.io/name: tezos-signer-forwarder
    app.kubernetes.io/baker-name: {{ .name }}
  ports:
  - port: 8443
    name: signer
  - port: 31732
    name: metrics
---
{{- end }}
