{{- range .Values.signers }}
{{- $name := .name }}
{{- $readiness_probe_path := .readiness_probe_path }}
{{- $signers := . }}
{{- range $i := until (len .endpoints) }}
{{- $endpoint := index $signers.endpoints $i }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-signer-forwarder-{{ $name}}-{{ $i }}
  annotations:
    "pulumi.com/skipAwait": "true"
spec:
  replicas: 1
  serviceName: tezos-remote-signer-{{ $name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tezos-signer-forwarder
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: tezos-signer-forwarder
        app.kubernetes.io/baker-name: {{ $name }}
    spec:
      volumes:
      - name: config-volume
        configMap:
           name: tezos-signer-forwarder-config-{{ $name }}-{{ $i }}
      - name: secret-volume
        secret:
           secretName: tezos-signer-forwarder-secret-{{ $.Values.name }}
           defaultMode: 0400
      containers:
      - name: tezos-signer-forwarder
        image: {{ $.Values.images.tezos_signer_forwarder }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
        args:
          - "-c"
          - |
{{ tpl ($.Files.Get (print "scripts/entrypoint.sh")) $ | indent 12 }}
        volumeMounts:
        - name: config-volume
          mountPath: /home/signer/.ssh/authorized_keys
          subPath: authorized_keys
        - name: secret-volume
          mountPath: /etc/ssh/ssh_host_ecdsa_key
          subPath: ssh_host_ecdsa_key
        env:
        - name: TUNNEL_ENDPOINT_PORT
          valueFrom:
            configMapKeyRef:
              name: tezos-signer-forwarder-config-{{ $name }}-{{ $i }}
              key: tunnel_endpoint_port
        ports:
        - name: signer
          containerPort: 8443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: {{ $readiness_probe_path }}
            port: 8443
      - name: prom-exporter
        image: {{ $.Values.tezos_k8s_images.utils }}
        ports:
          - name: metrics
            containerPort: 31732
            protocol: TCP
        env:
        - name: READINESS_PROBE_PATH
          value: {{ $readiness_probe_path | quote }}
        command:
          - /usr/local/bin/python
        args:
          - "-c"
          - |
{{ tpl ($.Files.Get (print "scripts/signer_exporter.py")) $ | indent 12 }}
      nodeSelector:
 {{ toYaml $.Values.node_selector | indent 8 }}
---
{{- end }}
{{- end }}
