apiVersion: v1
kind: Namespace
metadata:
  name: "tqtezos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tezos-pv-claim
  namespace: "tqtezos"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: tezos-secret
  namespace: "tqtezos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tqtezos-utils
  namespace: "tqtezos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: "tqtezos"
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  type: NodePort
  ports:
  - port: 8732
    nodePort: 31732
  selector:
    app: tezos-node
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-net
  namespace: "tqtezos"
spec:
  type: NodePort
  ports:
  - port: 9732
    nodePort: 30732
  selector:
    app: tezos-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-node
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-node
    spec:
      securityContext:
        fsGroup: 100
      initContainers:
      - imagePullPolicy: Always
        name: tezos-config-generator
        image: python:alpine
        command: ["python", "/opt/tqtezos/generateTezosConfig.py"]
        envFrom:
        - configMapRef:
            name: tezos-config
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: tqtezos-utils
          mountPath: /opt/tqtezos
        - name: var-volume
          mountPath: /var/tezos
      containers:
      - imagePullPolicy: Always
        name: tezos-node
        command: ["/usr/local/bin/tezos-node"]
        args: ["run", "--config-file",  "/etc/tezos/config.json"]
        readinessProbe:
          exec:
            command: ["nc", "-z", "127.0.0.1", "8732"]
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
        ports:
        - containerPort: 8732
          name: tezos-rpc
        - containerPort: 9732
          name: tezos-net
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: tqtezos-utils
        configMap:
          name: tqtezos-utils
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
