{{- define "tacoinfra-remote-signer.serviceAccount" }}
{{- $serviceAccount := $.signerConfig.serviceAccount | default dict }}

{{- if or $serviceAccount.create (not (hasKey $serviceAccount "create")) }}

{{- /* Set the SA name on $.signerConfig for the deployment to access */ -}}
{{- $_ := set $.signerConfig "serviceAccountName" ($serviceAccount.name | default $.signerName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name | default $.signerName }}
  {{- with $serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- end }}
