apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-faucet
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tezos-faucet
  template:
    metadata:
      labels:
        app: tezos-faucet
      annotations:
        # ensure that the pod bounces each time configmap changes
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
      - image: {{ .Values.images.tezosFaucetBackend }}
        name: faucet-backend
        ports:
        - name: backend
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: faucet-backend-config
        - secretRef:
            name: faucet-backend-secret
    {{- if .Values.enableUI }}
      - image: {{ .Values.images.tezosFaucet }}
        name: faucet
        ports:
        - name: frontend
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: faucet-config
          mountPath: /app/public/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: faucet-config
        configMap:
          name: faucet-config
    {{- end }}
