apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-faucet
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tezos-faucet
  template:
    metadata:
      labels:
        app: tezos-faucet
      annotations:
        # ensure that the pod bounces each time configmap changes
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }} 
    spec:
      containers:
      - image: {{ .Values.images.tezos_faucet_backend }}
        name: faucet-backend
        ports:
        - name: backend
          containerPort: 3000
          protocol: TCP
        env:
        - name: FAUCET_PRIVATE_KEY
          value: {{ .Values.faucetPrivateKey }}
        - name: FAUCET_ADDRESS
          value: {{ .Values.config.network.faucetAddress }}
        - name: FAUCET_CAPTCHA_SECRET
          value: {{ .Values.googleCaptchaSecretKey }}
        - name: RPC_URL
          value: {{ .Values.config.network.rpcUrl }}
        - name: AUTHORIZED_HOST
          value: {{ .Values.authorizedHost }}
        - name: FAUCET_AMOUNT_USER
          value:: {{ .Values.config.application.profiles.user.amount}}
        - name: FAUCET_AMOUNT_BAKER
          value:: {{ .Values.config.application.profiles.baker.amount}}
      - image: {{ .Values.images.tezos_faucet }}
        name: faucet
        ports:
        - name: frontend
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: faucet-config
          mountPath: "/app/src/config.json"
          subPath: "config.json"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: faucet-config
        configMap:
          name: faucet-config
status: {}
