apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-faucet
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tezos-faucet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tezos-faucet
    spec:
      containers:
      - image: {{ .Values.images.tezos_faucet_backend }}
        name: faucet-backend
        ports:
        - containerPort: 3000
        env:
        - name: FAUCET_PRIVATE_KEY
          value: {{ .Values.faucetPrivateKey }}
        - name: FAUCET_ADDRESS
          value: {{ .Values.config.network.faucetAddress }}
        - name: FAUCET_CAPTCHA_SECRET
          value: {{ .Values.googleCaptchaSecretKey }}
        - name: RPC_URL
          value: {{ .Values.config.network.rpcUrl }}
        - name: AUTHORIZED_HOST
          value: {{ .Values.authorizedHost }}
        - name: FAUCET_AMOUNT_USER
          value:: {{ .Values.config.application.profiles.user.amount}}
        - name: FAUCET_AMOUNT_BAKER
          value:: {{ .Values.config.application.profiles.baker.amount}}
      - image: {{ .Values.images.tezos_faucet }}
        name: faucet
        ports:
        - containerPort: 80
        volumeMounts:
        - name: faucet-config
          mountPath: "/config"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: faucet-config
        configMap:
          name: faucet-config
status: {}
