apiVersion: v1
kind: Service
metadata:
  labels:
    app: faucet
  name: tezos_faucet
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: faucet
status:
  loadBalancer: {}
