apiVersion: v1
kind: Secret
metadata:
  name: faucet-backend-secret
  namespace: {{ .Release.Namespace }}
data:
  CAPTCHA_SECRET: {{ .Values.googleCaptchaSecretKey | b64enc }}
  FAUCET_PRIVATE_KEY: {{ required "faucetPrivateKey is required." .Values.faucetPrivateKey | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
