apiVersion: v1
kind: Secret
metadata:
  name: faucet-secret
  namespace: {{ .Release.Namespace }}
data:
  recaptcha_keys.json: |
{{ .Values.recaptcha_keys | toJson | b64enc | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: faucet-backend-secret
  namespace: {{ .Release.Namespace }}
data:
  FAUCET_PRIVATE_KEY: {{ .Values.faucetPrivateKey | b64enc }}
  FAUCET_CAPTCHA_SECRET: {{ .Values.googleCaptchaSecretKey | b64enc }}
