apiVersion: v1
kind: Service
metadata:
  labels:
    app: tezos-faucet
  name: tezos-faucet
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 80
      targetPort: frontend
      protocol: TCP
    - name: backend
      port: 3000
      targetPort: backend
      protocol: TCP
  selector:
    app: faucet
status:
  loadBalancer: {}
