apiVersion: v1
kind: Service
metadata:
  labels:
    app: tezos-faucet
  name: tezos-faucet
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: tezos-faucet
  ports:
  {{- if .Values.enableUI }}
    - name: frontend
      port: 8080
      targetPort: frontend
      protocol: TCP
  {{- end }}
    - name: backend
      port: 3000
      targetPort: backend
      protocol: TCP
