preserved_cycles: 2
blocks_per_cycle: 8
blocks_per_commitment: 4
blocks_per_roll_snapshot: 4
blocks_per_voting_period: 64
time_between_blocks: ["10", "20"]
endorsers_per_block: 32
hard_gas_limit_per_operation: "800000"
hard_gas_limit_per_block: "8000000"
proof_of_work_threshold: "-1"
tokens_per_roll: "8000000000"
michelson_maximum_type_size: 1000
seed_nonce_revelation_tip: "125000"
origination_size: 257
block_security_deposit: "512000000"
endorsement_security_deposit: "64000000"
endorsement_reward: ["2000000"]
cost_per_byte: "1000"
hard_storage_limit_per_operation: "60000"
quorum_min: 2000
quorum_max: 7000
min_proposal_quorum: 500
initial_endorsers: 1
delay_per_missing_endorsement: "1"
baking_reward_per_endorsement: ["200000"]
minimal_block_delay: "2"
liquidity_baking_subsidy: "2500000"
liquidity_baking_sunset_level: 525600
liquidity_baking_escape_ema_threshold: 100000
