preserved_cycles: 3
blocks_per_cycle: 8
blocks_per_commitment: 4
blocks_per_stake_snapshot: 4
cycles_per_voting_period: 1
hard_gas_limit_per_operation: '1040000'
hard_gas_limit_per_block: '5200000'
proof_of_work_threshold: '-1'
minimal_stake: '6000000000'
seed_nonce_revelation_tip: '125000'
baking_reward_fixed_portion: '10000000'
baking_reward_bonus_per_slot: '4286'
endorsing_reward_per_slot: '2857'
hard_storage_limit_per_operation: '60000'
origination_size: 257
cost_per_byte: '250'
quorum_max: 7000
quorum_min: 2000
min_proposal_quorum: 500
liquidity_baking_subsidy: '2500000'
liquidity_baking_toggle_ema_threshold: 100000
max_operations_time_to_live: 120
minimal_block_delay: "5"
delay_increment_per_round: "5"
consensus_committee_size: 7000
consensus_threshold: 4667
minimal_participation_ratio:
  numerator: 2
  denominator: 3
max_slashing_period: 2
frozen_deposits_percentage: 10
double_baking_punishment: "640000000"
ratio_of_frozen_deposits_slashed_per_double_endorsement:
  numerator: 1
  denominator: 2
cache_script_size: 100000000
cache_stake_distribution_cycles: 8
cache_sampler_state_cycles: 8
nonce_revelation_threshold: 4
vdf_difficulty: '100000'
tx_rollup_enable: false
tx_rollup_origination_size: 4000
tx_rollup_hard_size_limit_per_inbox: 500000
tx_rollup_hard_size_limit_per_message: 5000
tx_rollup_commitment_bond: "10000000000"
tx_rollup_finality_period: 10
tx_rollup_max_inboxes_count: 15
tx_rollup_withdraw_period: 10
tx_rollup_max_messages_per_inbox: 1010
tx_rollup_max_commitments_count: 30
tx_rollup_cost_per_byte_ema_factor: 120
tx_rollup_max_withdrawals_per_batch: 15
tx_rollup_max_ticket_payload_size: 2048
tx_rollup_rejection_max_proof_size: 30000
tx_rollup_sunset_level: 10000000
dal_parametric:
  feature_enable: true
  number_of_slots: 256
  number_of_shards: 2048
  attestation_lag: 2
  attestation_threshold: 50
  slot_size: 1048576
  redundancy_factor: 16
  page_size: 4096
  blocks_per_epoch: 8
smart_rollup_enable: true
smart_rollup_origination_size: 6314
smart_rollup_challenge_window_in_blocks: 40
smart_rollup_stake_amount: "32000000"
smart_rollup_commitment_period_in_blocks: 20
smart_rollup_max_lookahead_in_blocks: 30000
smart_rollup_max_active_outbox_levels: 20160
smart_rollup_max_outbox_messages_per_level: 100
smart_rollup_number_of_sections_in_dissection: 32
smart_rollup_timeout_period_in_blocks: 500
smart_rollup_max_number_of_cemented_commitments: 5
smart_rollup_max_number_of_parallel_games: 32
smart_rollup_arith_pvm_enable: true
zk_rollup_enable: true
zk_rollup_origination_size: 4000
zk_rollup_min_pending_to_process: 10
