preserved_cycles: 3
blocks_per_cycle: 8
blocks_per_commitment: 4
blocks_per_stake_snapshot: 4
blocks_per_voting_period: 64
hard_gas_limit_per_operation: '1040000'
hard_gas_limit_per_block: '5200000'
proof_of_work_threshold: '-1'
tokens_per_roll: '8000000000'
seed_nonce_revelation_tip: '125000'
baking_reward_fixed_portion: '10000000'
baking_reward_bonus_per_slot: '4286'
endorsing_reward_per_slot: '2857'
hard_storage_limit_per_operation: '60000'
origination_size: 257
cost_per_byte: '1000'
quorum_max: 7000
quorum_min: 2000
min_proposal_quorum: 500
liquidity_baking_subsidy: '2500000'
liquidity_baking_sunset_level: 525600
liquidity_baking_escape_ema_threshold: 100000
max_operations_time_to_live: 120
minimal_block_delay: "5"
delay_increment_per_round: "5"
consensus_committee_size: 7000
consensus_threshold: 4667
minimal_participation_ratio:
  numerator: 2
  denominator: 3
max_slashing_period: 2
frozen_deposits_percentage: 10
double_baking_punishment: "640000000"
ratio_of_frozen_deposits_slashed_per_double_endorsement:
  numerator: 1
  denominator: 2
