preserved_cycles: 3
blocks_per_cycle: 8
blocks_per_commitment: 4
blocks_per_stake_snapshot: 4
cycles_per_voting_period: 1
hard_gas_limit_per_operation: '1040000'
hard_gas_limit_per_block: '5200000'
proof_of_work_threshold: '-1'
minimal_stake: '6000000000'
minimal_frozen_stake: '600000000'
adaptive_issuance_launch_ema_threshold: 10000000
adaptive_issuance_activation_vote_enable: false
autostaking_enable: true
global_limit_of_staking_over_baking: 5
edge_of_staking_over_delegation: 2
adaptive_rewards_params:
  issuance_ratio_min:
    numerator: "1"
    denominator: "200"
  issuance_ratio_max:
    numerator: "1"
    denominator: "10"
  max_bonus: "50000000000000"
  growth_rate:
    numerator: "1"
    denominator: "100"
  center_dz:
    numerator: "1"
    denominator: "2"
  radius_dz:
    numerator: "1"
    denominator: "50"
issuance_weights:
  base_total_issued_per_minute: "85007812"
  baking_reward_fixed_portion_weight: 5120
  baking_reward_bonus_weight: 5120
  attesting_reward_weight: 10240
  liquidity_baking_subsidy_weight: 1280
  vdf_revelation_tip_weight: 1
  seed_nonce_revelation_tip_weight: 1
hard_storage_limit_per_operation: '60000'
origination_size: 257
cost_per_byte: '250'
quorum_max: 7000
quorum_min: 2000
min_proposal_quorum: 500
liquidity_baking_toggle_ema_threshold: 100000
max_operations_time_to_live: 120
minimal_block_delay: "5"
delay_increment_per_round: "5"
consensus_committee_size: 7000
consensus_threshold: 4667
minimal_participation_ratio:
  numerator: 2
  denominator: 3
limit_of_delegation_over_baking: 9
percentage_of_frozen_deposits_slashed_per_double_baking: 7
percentage_of_frozen_deposits_slashed_per_double_attestation: 50
cache_script_size: 100000000
cache_stake_distribution_cycles: 8
cache_sampler_state_cycles: 8
nonce_revelation_threshold: 4
vdf_difficulty: '100000'
dal_parametric:
  feature_enable: true
  number_of_slots: 256
  number_of_shards: 2048
  attestation_lag: 2
  attestation_threshold: 50
  slot_size: 65536
  redundancy_factor: 16
  page_size: 4096
  blocks_per_epoch: 8
smart_rollup_private_enable: true
smart_rollup_riscv_pvm_enable: true
smart_rollup_origination_size: 6314
smart_rollup_challenge_window_in_blocks: 40
smart_rollup_stake_amount: "32000000"
smart_rollup_commitment_period_in_blocks: 20
smart_rollup_max_lookahead_in_blocks: 30000
smart_rollup_max_active_outbox_levels: 20160
smart_rollup_max_outbox_messages_per_level: 100
smart_rollup_number_of_sections_in_dissection: 32
smart_rollup_timeout_period_in_blocks: 500
smart_rollup_max_number_of_cemented_commitments: 5
smart_rollup_max_number_of_parallel_games: 32
smart_rollup_arith_pvm_enable: true
smart_rollup_reveal_activation_level:
  raw_data:
    Blake2B: 0
  metadata: 0
  dal_page: 0
  dal_parameters: 0
zk_rollup_enable: true
zk_rollup_origination_size: 4000
zk_rollup_min_pending_to_process: 10
zk_rollup_max_ticket_payload_size: 2048
