apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-rpc
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-net
  namespace: "tqtezos"
spec:
  ports:
  - port: 8733
  selector:
    app: tezos-net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-node
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-node
    spec:
      containers:
      - image: {docker_image}
        imagePullPolicy: Always
        name: tezos-node
        command: ["/usr/local/bin/tezos-node"]
        args: ["run", "--config-file",  "/etc/tezos/config.json"]
        ports:
        - containerPort: 8732
          name: tezos-rpc
        - containerPort: 8733
          name: tezos-net
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
