# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2.2"

gem "webrick", "~> 1.7"

gem "jekyll-datapage-generator"

gem "jekyll-remote-theme"