{{- if (include "tezos.shouldActivateProtocol" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: activate-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: activate-job
    spec:
      containers:
        - image: "{{ .Values.images.tezos }}"
          command:
            - /bin/sh
          args:
            - "-c"
            - |
{{ tpl (.Files.Get "scripts/chain-initiator.sh") . | indent 14 }}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.chain_initiator_job.name }}
          volumeMounts:
            - mountPath: /etc/tezos
              name: config-volume
            - mountPath: /var/tezos
              name: var-volume
          envFrom:
            - configMapRef:
                name: tezos-config
      initContainers:
        - image: {{ .Values.tezos_k8s_images.utils }}
          imagePullPolicy: IfNotPresent
          name: config-generator
          args:
            - config-generator
            - "--generate-parameters-json"
          envFrom:
            - secretRef:
                name: tezos-secret
            - configMapRef:
                name: tezos-config
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_TYPE
              value: {{ .Values.chain_initiator_job.pod_type }}
          volumeMounts:
            - mountPath: /etc/tezos
              name: config-volume
            - mountPath: /var/tezos
              name: var-volume
      restartPolicy: Never
      volumes:
        - emptyDir: {}
          name: config-volume
        - emptyDir: {}
          name: var-volume
{{ end }}
