{{- range $k, $v := .Values.smartRollupNodes }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.smart_rollup_node_statefulset.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: web
  selector:
    app: {{ $.Values.smart_rollup_node_statefulset.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $k }}
  namespace: {{ $.Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: {{ $.Values.smart_rollup_node_statefulset.name }}
  selector:
    matchLabels:
      app: {{ $.Values.smart_rollup_node_statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.smart_rollup_node_statefulset.name }}
    spec:
      containers:
      - name: octez-smart-rollup-node
        image: "{{ $.Values.images.octez }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
        command:
          - /bin/sh
        volumeMounts:
        - mountPath: /var/tezos
          name: var-volume
        args:
          - "-c"
          - |
{{ tpl ($.Files.Get "scripts/smart-rollup-node.sh") $ | indent 12 }}
        env:
          - name: ROLLUP_ADDRESS
            value: {{ $v.rollup_address }}
          - name: OPERATOR_ACCOUNT
            value: {{ $v.operator_account }}
      initContainers:
      - image: {{ $.Values.tezos_k8s_images.utils }}
        imagePullPolicy: IfNotPresent
        name: config-generator
        args:
          - "config-generator"
        envFrom:
          - configMapRef:
              name: tezos-config
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_TYPE
            value: {{ $.Values.smart_rollup_node_statefulset.pod_type }}
        volumeMounts:
          - mountPath: /var/tezos
            name: var-volume
          - mountPath: /etc/secret-volume
            name: tezos-accounts
      securityContext:
        fsGroup: 1000
      volumes:
        - emptyDir: {}
          name: var-volume
        - name: tezos-accounts
          secret:
            secretName: tezos-secret
---
{{- end }}
