{{- if (include "tezos.shouldDeploySignerStatefulset" .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.signer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.signers | len }}
  serviceName: {{ .Values.signer_statefulset.name }}
  selector:
    matchLabels:
      app: {{ .Values.signer_statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.signer_statefulset.name }}
    spec:
      containers:
      - name: tezos-signer
        image: "{{ .Values.images.tezos }}"
        ports:
        - containerPort: 6732
          name: signer
        command:
          - /bin/sh
        volumeMounts:
        - mountPath: /var/tezos
          name: var-volume
        args:
          - "-c"
          - |
{{ tpl (.Files.Get "scripts/remote-signer.sh") $ | indent 12 }}
      initContainers:
      - image: {{ .Values.tezos_k8s_images.utils }}
        imagePullPolicy: IfNotPresent
        name: config-generator
        args:
          - "config-generator"
        envFrom:
          - secretRef:
              name: tezos-secret
          - configMapRef:
              name: tezos-config
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_TYPE
            value: {{ .Values.signer_statefulset.pod_type }}
        volumeMounts:
          - mountPath: /var/tezos
            name: var-volume
      securityContext:
        fsGroup: 100
      volumes:
        - emptyDir: {}
          name: var-volume
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.signer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 6732
      name: signer
  selector:
    app: {{ .Values.signer_statefulset.name }}
---
{{- end }}
