kind: Secret
apiVersion: v1
metadata:
  name: s3-secrets
data:
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3_secret_access_key | b64enc }}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: s3-env
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.s3_access_key_id }}"
  BUCKET_ENDPOINT_URL: "{{ .Values.bucket_endpoint_url }}"
  BUCKET_NAME: "{{ .Values.bucket_name}}"
  BUCKET_REGION: "{{ .Values.bucket_region}}"
  PROTO_NAME: "{{ .Values.proto_name}}"
  VANITY_STRING: "{{ .Values.vanity_string}}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: scripts
data:
  proto-cruncher.py: |
{{ tpl ($.Files.Get (print "scripts/proto-cruncher.py")) $ | indent 4 }}
  proto-downloader.py: |
{{ tpl ($.Files.Get (print "scripts/proto-downloader.py")) $ | indent 4 }}
