kind: Secret
apiVersion: v1
metadata:
  name: s3-secrets
data:
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3SecretAccessKey | b64enc }}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: s3-env
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.s3AccessKeyId }}"
  BUCKET_ENDPOINT_URL: "{{ .Values.bucketEndpointUrl }}"
  BUCKET_NAME: "{{ .Values.bucketName}}"
  BUCKET_REGION: "{{ .Values.bucketRegion}}"
  PROTO_NAME: "{{ .Values.protoName}}"
  VANITY_STRING: "{{ .Values.vanityString}}"
  NUM_NONCE_DIGITS: "{{ .Values.numNonceDigits }}"
  NUM_PARALLEL_PROCESSES: "{{ .Values.numParallelProcesses }}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: scripts
data:
  tezos-proto-cruncher.py: |
{{ tpl ($.Files.Get (print "scripts/tezos-proto-cruncher.py")) $ | indent 4 }}
