{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: polkadot-metrics
  name: polkadot-service-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: pyrometer
{{- end }}
