apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iam_role_arn }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-volumesnapshots
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io", "batch", ""]
    resources:
      - volumesnapshots
      - volumesnapshotcontents
      - jobs
      - persistentvolumeclaims
      - configmaps
      - pods
    verbs:
      - get
      - list
      - delete
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshots-for-sa
  namespace: {{ $.Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service_account }}
roleRef:
  kind: Role
  name: modify-volumesnapshots
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-service-accounts" "list-volumesnapshotcontents-for" $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-volumesnapshotcontents
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ .Values.service_account }}
  namespace: {{ $.Release.Namespace }}