{{ define "snapshot-warmer.name" }}
{{- $history_mode := $.history_mode }}
  {{- printf "%s-%s-%s" "snapshot-warmer-for" $history_mode "node" }}
{{- end }}

{{- range $node, $config := .Values.nodes }}
{{- if $config }}
  {{- $_ := set $ "history_mode" $config.history_mode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snapshot-warmer.name" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "snapshot-warmer.name" $ }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "snapshot-warmer.name" $ }}
  template:
    metadata:
      labels:
        app: {{ include "snapshot-warmer.name" $ }}
    spec:
      serviceAccountName: {{ $.Values.service_account }}
      containers:
        - name: {{ include "snapshot-warmer.name" $ }}
          image: {{ $.Values.tezos_k8s_images.snapshotEngine }}
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
{{ $.Files.Get "scripts/snapshot-warmer.sh" | indent 14 }}
          env:
            - name: VOLUME_SNAPSHOT_CLASS
              value: {{ $.Values.volumeSnapClass }}
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
            - name: NODE_CLASS
              value: {{ $node }}
            - name: NODE_CONFIG
              value: {{ $config | toJson | quote }}
---
{{- end }}
{{- end }}
