apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tezos-reward-distributor.fullname" . }}-volume
spec:
 storageClassName:
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
