apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-cache-volume
  namespace: hangzhounet-shots
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
