apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-cache-volume
  namespace: ""
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
