apiVersion: batch/v1
kind: Job
metadata:
  name: snapshot-maker
  namespace: ""
spec:
  template:
    metadata:
      labels:
        app: snapshot-maker
    spec:
      serviceAccountName: ""
      containers:
        - name: snapshot-maker
          image: ""
          imagePullPolicy: Never
          args:
              - "snapshot-maker"
          env:
            - name: HISTORY_MODE
              value: ""
          envFrom:
            - configMapRef:
                name: snapshot-configmap
      restartPolicy: Never
