apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ""
  namespace: ""
spec:
  storageClassName: ebs-sc
  dataSource:
    name: ""
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ""
